name: CI/CD Workflow

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t inter_cloud-db1 .

    - name: Save Docker image as tar
      run: docker save inter_cloud-db1 > inter_cloud-web.tar

    - name: Copy image to server (optional)
      # Folosești SCP dacă rulezi Kubernetes în afara GitHub (ex: Minikube local)
      # Acest pas poate fi omis dacă nu ai server extern.

    - name: Deploy to Kubernetes (optional)
      run: |
        kubectl apply -f mysql-deployment.yaml
        kubectl apply -f mysql-service.yaml
        kubectl apply -f web-deployment.yaml
        kubectl apply -f web-service.yaml
